apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: gitlab
    gitName: gitlab
    gitServer: http://gitlab.infra.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: devopsman
    repository: install-jx
  - key: staging
  - key: production
  ingress:
    domain: devopsman.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: devopsman-jx-bot
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
