apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: commit-infra
spec:
  params:
    - name: commit-id
    - name: commit-describe
    - name: repo-infra
      description: Git repository containing manifest files to update
      default: gitlab.infra.local/devopsman/jx-demo-infra.git
    - name: deploy-path
      description: Manifests files dir
      default: jx-demo
    - name: commit-image
#      default: cnych/helm-kubectl-curl-git-jq-yq
      default: harbor.devopsman.io/devopsman/commit-infra:v1.1
    - name: git-email
      default: devopsman-jx-bot@cloudtogo.cn
    - name: git-name
      default: devopsman-jx-bot
  steps:
    - name: update-yaml-push
      image: $(params.commit-image)
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-token
              key: username
              optional: true
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: github-token
              key: password
              optional: true
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -eu
          echo Load environment variables from previous steps
          # source /workspace/env-config
          git config --global user.email "$(params.git-email)"
          git config --global user.name "$(params.git-name)"
          git clone --branch master --depth 1 https://${GIT_USERNAME}:${GIT_PASSWORD}@$(params.repo-infra) repo
          cd "repo/$(params.deploy-path)"
          ls -l
          echo old value and set to image.oldtag:
          cat values.yaml | yq r - 'image.tag'
          yq w -i values.yaml 'image.oldtag' $(/bin/cat values.yaml | yq r - 'image.tag')
          echo replacing with new value
          yq w -i values.yaml 'image.tag' "$(params.commit-id)"
          echo verifying new value
          yq r values.yaml image.tag
          if ! git diff-index --quiet HEAD --; then
            git status
            git add .
            git commit -m "Auto: $(params.commit-describe)"
            git push
          else
              echo "no changes, git repository is up to date"
          fi
