apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-test-simple
spec:
  workspaces:
    - name: output
  params:
    - name: package
      description: package (and its children) under test
  steps:
    - name: go-test
      image: golang:alpine  #使用alpine时 单元测试特意报错，正常使用latest
#      image: golang:latest
      script: |
        echo "Begining to go test"
        cd $(workspaces.output.path)
        ls -la
        go test .
