apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jwt-demo-pipeline-run
  namespace: jx
spec:
  pipelineRef:
    name: jwt-demo-pipeline
  workspaces:
    - name: source-workspace
      subPath: source
      persistentVolumeClaim:
        claimName: e2e-stress-source-pvc
    - name: cache-workspace
      subPath: cache
      persistentVolumeClaim:
        claimName: e2e-stress-source-pvc
  params:
    - name: repo-url
      value: "https://gitlab.infra.local/devopsman/jx-demo" #code repo
    - name: repo-revision
      value: "core"
    - name: svc-addrs
      value: "http://jx-demo.default:80/"
    - name: repo-image
      value: "devopsman/jx-demo"  #image url for docker registry
    - name: repo-infra
      value: "gitlab.infra.local/devopsman/jx-demo-infra" #这里不要带https
    - name: deploy-path
      value: "staging/jx-demo"
    - name: prod-deploy-path
      value: "prod/jx-demo"


  serviceAccountName: buildpacks-service-account
