apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jwt-demo-pipeline
  namespace: jx
spec:
  workspaces:
    - name: source-workspace  # Directory where application source is located.
    # - name: cache-workspace # Directory where cache is stored
  params:
    - name: svc-addrs
      type: string
    - name: repo-url
    - name: repo-revision
      type: string
      default: "master"
    - name: repo-image
    - name: repo-infra
    - name: deploy-path
    - name: prod-deploy-path

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: deleteExisting
          value: "true"
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)

    - name: e2e-test
      taskRef:
        name: e2e-test
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source-workspace
      params:
        - name: addrs
          value: $(params.svc-addrs)
        - name: E2E_STRESS_IMAGE
          value: harbor.devopsman.io/devopsman/go-e2e-stress-tool:v3

    - name: stress-test
      taskRef:
        name: stress-test
      runAfter:
        - git-clone
      params:
        - name: addrs
          value: $(params.svc-addrs)
        - name: E2E_STRESS_IMAGE
          value: harbor.devopsman.io/devopsman/go-e2e-stress-tool:v3

    - name: sync-staging-to-prod
      taskRef:
        name: sync-staging-to-prod
      runAfter:
        - git-clone
        - e2e-test
        - stress-test
      params:
        - name: repo-infra
          value: $(params.repo-infra)
        - name: deploy-path
          value: $(params.deploy-path)
        - name: prod-deploy-path
          value: $(params.prod-deploy-path)
        - name: commit-describe
          value: $(tasks.git-clone.results.describe)
