apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko
  namespace: jx
spec:
  params:
    - name: repo-url
      type: string
    - default: master
      name: repo-revision
      type: string
  tasks:
    - name: git-clone
      params:
        - name: deleteExisting
          value: 'true'
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
    - name: kaniko
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: kaniko
      workspaces:
        - name: output
          workspace: source-workspace
  workspaces:
    - name: source-workspace