apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jx-demo-pipeline
spec:
  workspaces:
    - name: source-workspace  # Directory where application source is located.
    - name: cache-workspace # Directory where cache is stored
  params:
    - name: repo-url
    - name: repo-revision
      type: string
      default: "master"
    - name: repo-image
    - name: repo-infra
    - name: deploy-path

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: deleteExisting
          value: "true"
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
    - name: buildpacks
      taskRef:
        name: buildpacks
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source-workspace
        - name: cache
          workspace: cache-workspace
      params:
        - name: BUILDER_IMAGE
          value: harbor.devopsman.io/devopsman/buildpacks-ca:20
#          value: heroku/buildpacks:20
        - name: APP_IMAGE
          value: $(params.repo-image):$(tasks.git-clone.results.commit)
        - name: ENV_VARS  #测试变量
          value:
            - "GOPROXY=https://goproxy.cn"
            - "GO111MODULE=auto"
            - "GOPRIVATE=gitlab.infra.local"
    - name: display-results
      runAfter:
        - buildpacks
      taskRef:
        name: display-results
      workspaces:
        - name: output
          workspace: source-workspace
        - name: cache
          workspace: cache-workspace
      params:
        - name: DIGEST
          value: $(tasks.buildpacks.results.APP_IMAGE_DIGEST)
        - name: URL
          value: $(tasks.buildpacks.results.APP_IMAGE_URL)
        - name: COMMIT
          value: $(tasks.git-clone.results.commit)

    - name: commit-infra
      taskRef:
        name: commit-infra
      runAfter:
        - buildpacks
      params:
        - name: commit-id
          value: $(tasks.git-clone.results.commit)
        - name: commit-describe
          value: $(tasks.git-clone.results.describe)
        - name: repo-infra
          value: $(params.repo-infra)
        - name: deploy-path
          value: $(params.deploy-path)
