apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: unit-test-pipeline
spec:
  workspaces:
    - name: source-workspace  # Directory where application source is located.
  params:
    - name: repo-url
    - name: repo-revision
      type: string
      default: "master"
    - name: package
      default: "jx-demo"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: deleteExisting
          value: "true"
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
    - name: golangci-lint
      taskRef:
        name: golangci-lint
      runAfter:
        - git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: package
          value: $(params.package)
    #    - name: code-analysis
    #      taskRef:
    #        name: sonarqube-scanner
    #      runAfter:
    #        - git-clone
    #      params:
    #        - name: SONAR_HOST_URL
    #          value: http://10.10.11.106:9000
    #        # value: http://sonarqube.devopsman.io
    #        - name: SONAR_LOGIN
    #          value: 469d3fcce520017e0cd699706404a4db8a1938e9
    #        # value: 2eff6e1e5acb83cd6716b7656b198cf4518dcc3b
    #        - name: SONAR_PROJECT_KEY
    #          value: devopsman_jx-demo_AX8klNKSC0ZQ0grt_Om4
    #        # value: devopsman_jx-demo_AX8kNOfSiMma7ZsplPQi
    #      workspaces:
    #        - name: output
    #          workspace: source-workspace
    #        - name: sonar-settings
    #          workspace: source-workspace
    - name: golang-test
      taskRef:
        name: golang-test
      #        name: golang-test-simple
      runAfter:
        - golangci-lint
      #        - git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: package
          value: $(params.package)
        - name: packages
          value: "."


