apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: unit-test-pipeline
spec:
  workspaces:
    - name: source-workspace  # Directory where application source is located.
  params:
    - name: repo-url
    - name: repo-revision
      type: string
      default: "master"
    - name: package
      default: "jx-demo"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: deleteExisting
          value: "true"
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
    - name: golangci-lint
      taskRef:
        name: golangci-lint
      runAfter:
        - git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: package
          value: $(params.package)
    - name: unit-test
      taskRef:
        name: unit-test
      runAfter:
        - golangci-lint
      workspaces:
        - name: output
          workspace: source-workspace


