approve:
  - lgtm_acts_as_approve: false
    repos:
      - devopsman/jx-demo
      - devopsman/install-jx
    require_self_approval: true
config_updater:
  gzip: false
  maps:
    config.yaml:
      name: config
    plugins.yaml:
      name: plugins
external_plugins:
  entries:
    - name: cd-indicators
      endpoint: "http://cd-indicators.jx.svc.cluster.local/lighthouse/events"
    - name: lighthouse-webui-plugin
      endpoint: "http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events"
triggers:
  - repos:
      - devopsman/jx-demo
      - devopsman/install-jx
    ignore_ok_to_test: false
    elide_skipped_contexts: false
plugins:
  devopsman:
    - config-updater
    - approve
    - assign
    - help
    - hold
    - lgtm
    - lifecycle
    - size
    - trigger
    - wip
    - cat
    - yuks
    - label
    - milestone
    - milestonestatus
    - owners-label
    - shrug
    - sigmention
    - skip
    - stage
    - override
    - branchcleaner
    - blockade
welcome:
  - message_template: Welcome
