apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  annotations:
#    tekton.dev/docker-0: https://index.docker.io/v1/
    tekton.dev/docker-0: http://harbor.devopsman.io
type: kubernetes.io/basic-auth
stringData:
  username: "admin"
  password: "Harbor12345"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
stringData:
  username: "rubinus"
  password: "Vbm-XynkoCyC-jyyoDhV"

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: argocd-oauth
#type: Opaque
#stringData:
#  username: admin
#  password: argocdadmin


